[build]
  publish = "_site"
  command = "npm run build"
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [ ".cache" ]
[[redirects]]
  from = "/apps/quick-snips/*"
  to = "https://quick-snips.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/apps/widget-dashboard/*"
  to = "https://widget-dashboard-demo.netlify.app/:splat"
  status = 200
