backend:
  name: git-gateway
  branch: main

media_folder: "src/static/img"
public_folder: "/static/img"

site_url: https://andy.bond
#logo_url: https://your-site.com/images/logo.svg

local_backend: true
publish_mode: editorial_workflow

editor:
  preview: false

collections:
  - label: "Posts"
    name: "posts"
    folder: "src/posts"
    path: "{{slug}}/index"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "categories",
          search_fields: ["posts.*.name"],
          value_field: "posts.*.name",
        }
  - label: "Photos"
    name: "photos"
    files:
      - label: "Gallery"
        name: "gallery"
        file: "src/_data/gallery.json"
        fields:
          - label: "Photos"
            name: "photos"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - {
                  label: "Photo",
                  name: "photo",
                  widget: "image",
                  media_folder: "/src/photos",
                  public_folder: "",
                }
              - {
                  label: "Category",
                  name: "category",
                  widget: "relation",
                  collection: "categories",
                  search_fields: ["photos.*.name"],
                  value_field: "photos.*.name",
                }
              - {
                  label: "Size",
                  name: "size",
                  widget: "select",
                  options: ["auto", "tall", "wide", "both"],
                  default: ["auto"]
                }
  - label: "Reviews"
    name: "reviews"
    folder: "src/reviews"
    path: "{{slug}}/index"
    create: true
    fields:
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "categories",
          search_fields: ["reviews.*.name"],
          value_field: "reviews.*.name",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Author (book) / Artist (music) / Developer (game) / Location (restaurant)",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Image", name: "image", widget: "image", choose_url: false }
      - { label: "Series", name: "series", widget: "string", required: false }
      - {
          label: "External Link",
          name: "externalLink",
          widget: "string",
          required: false,
        }
      - {
          label: "Rating",
          name: "rating",
          widget: "number",
          value_type: "int",
          hint: "1 - Unbearable, 2 - Painful, 3 - Awful, 4 - Bad, 5 - Mediocre, 6 - Okay, 7 - Good, 8 - Great, 9 - Amazing, 10 - Masterpiece",
          min: 1,
          max: 10,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Review", name: "body", widget: "markdown", required: false }
  - label: "Categories"
    name: "categories"
    files:
      - label: "Categories"
        name: "categories"
        file: "src/_data/categories.json"
        fields:
          - label: "Review Categories"
            name: "reviews"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
          - label: "Photo Categories"
            name: "photos"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
          - label: "Post Categories"
            name: "posts"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
  - label: "Settings"
    name: "settings"
    files:
      - label: "Navigation"
        name: "navigation"
        file: "src/_data/navigation.json"
        fields:
          - label: Nav Items
            name: items
            widget: list
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Metadata"
        name: "metadata"
        file: "src/_data/metadata.json"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Repository, name: repository, widget: string }
          - { label: Copyright Year, name: copyright, widget: number }
