backend:
  name: git-gateway
  branch: main

media_folder: "src/static/img"
public_folder: "/static/img"

site_url: https://andy.bond
#logo_url: https://your-site.com/images/logo.svg

local_backend: true
publish_mode: editorial_workflow

collections:
  - label: "Posts"
    name: "posts"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["life", "travel"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Metadata"
        name: "metadata"
        file: "src/_data/metadata.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Repository, name: repository, widget: string }
          - { label: Copyright Year, name: copyright, widget: number }
