name: Scheduled Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5/12 * * *'
jobs:
  build:
    name: Build Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} ${{ secrets.BUILD_URL }}?trigger_branch=main&trigger_title=Scheduled+Github+build&clear_cache=true
